name: 12h Stream
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: |
          sudo apt-get update && sudo apt install ffmpeg -y
          URL="https://drive.google.com/uc?export=download&id=1yGFyPE1bccQjB5FIqJqvJZw1uYLSqu6B"
          ffmpeg -re -stream_loop -1 -i "$URL" -c copy -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
